---
letsencrypt_email: prometheus-team@googlegroups.com
port_mapping:
  grafana: 3000
  prometheus: 9090
  alertmanager: 9093
  node: 9100

caddy_download: false
caddy_update: false
caddy_systemd_capabilities_enabled: true
caddy_systemd_restart_startlimitinterval: 3600
caddy_features: http.prometheus
caddy_config: |
  {{ ansible_host }} {
    ext .html
    root /var/www/demo/
    prometheus
    tls {{ letsencrypt_email }}
  }
  {% for name, port in port_mapping.items() %}
  {{ name }}.{{ ansible_host }} {
    proxy / 127.0.0.1:{{ port }}
    tls {{ letsencrypt_email }}
  }
  {% endfor %}
