---
- name: Install python
  hosts: all
  gather_facts: false
  tasks:
  - name: Install python
    raw: "apt update && apt install -y python3"

- name: Apply security restrictions
  hosts: all
  roles:
  - dev-sec.ssh-hardening
  - dev-sec.os-hardening
  tasks:
  - name: Set file descriptor limits
    pam_limits:
      dest: '/etc/security/limits.d/20.nofile.conf'
      domain: '*'
      limit_type: "{{ item }}"
      limit_item: nofile
      value: 16384
    with_items:
      - soft
      - hard
  vars:
    ssh_permit_root_login: "without-password"
