---
- name: Setup HTTP server
  hosts: web
  roles:
  - caddy_ansible.caddy_ansible
  pre_tasks:
  - name: Ensure webdirs exists
    file:
      path: "{{ item }}"
      state: directory
    with_items:
    - /var/www/demo
    - /var/www/demo/img
  - name: Ensure portal site exists
    copy:
      src: index.html
      dest: /var/www/demo/index.html
  - name: Copy digitalocean image
    copy:
      src: "https://github.com/prometheus/demo-site/raw/prometheus/playbooks/files/img/digitalocean.png"
      dest: "/var/www/demo/img/digitalocean.png"
